import type { Metadata } from 'next';
import localFont from 'next/font/local';
import Header from '@/components/ui/Header';
import Footer from '@/components/ui/Footer';
import Providers from '@/components/provider/Provider';
import './globals.css';

export const metadata: Metadata = {
  title: `Дистриб'ютор пива ТОВ "Антип"`,
  description: 'Generated by create next app',
};

export const cooperFont = localFont({
  src: '../public/font/Cooper[wght].woff2'
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang='en'>
      <body
        className={`${cooperFont.className} bg-[#F6EFE7]`}
      >
        <Providers>
          <div className='flex justify-center items-center h-[40px] w-full bg-[#4d6d7e]'>
            <span className='text-white font-extrabold text-[14px] text-center mx-[20px]'>Distributor of the best regional producers</span>
          </div>
          <Header />
          {children}
          <Footer />
        </Providers>
        <div id='portal'></div>
      </body>
    </html>

  );
}
