import type { Metadata } from 'next';
import './globals.css';
import localFont from 'next/font/local';
import Header from '@/components/ui/Header';

export const metadata: Metadata = {
  title: `Дистриб'ютор пива ТОВ "Антип"`,
  description: 'Generated by create next app',
};

export const cooperFont = localFont({
  src: '../public/font/Cooper[wght].woff2'
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang=''>
      <body
        className={`${cooperFont.className}`}
      >
        <div className='flex justify-center items-center h-[40px] w-full bg-[#4d6d7e]'>
          <span className='text-white font-extrabold text-[14px] text-center mx-[20px]'>Leading distributor of regional beer in Ukraine</span>
        </div>
        <Header />
        {children}
        <div id='portal'></div>
      </body>
    </html>
  );
}
